name: dict-cc
version: 0.1.0
category: Web
synopsis: Command line client for https://dict.cc
description: |
    A command line client for dict.cc which is based on scraping
    the webpage (since no API is provided).

    The key features are

     * filtering based on word category (e.g. verb, noun)
     * translations between different languages
     * defining frequently used settings in a central config file

github: matt-snider/dict.cc
license: MIT

author: Matt Snider
maintainer: Matt Snider <matt.snider@alum.utoronto.ca>
copyright: (c) 2018 Matt Snider

extra-source-files:
  - README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extension:
- ConstraintKinds
- DataKinds
- DeriveFunctor
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators


dependencies:
  - base >= 4.9 && < 5

executables:
  dict-cc:
    source-dirs: src/
    main: Main.hs
    dependencies:
    - bytestring == 0.10.8.1
    - directory == 1.3.0.0
    - http-conduit >= 2.2.3.2
    - HTTP >= 4000
    - regex-posix == 0.95.2
    - tagsoup == 0.14.1
    - text == 1.2.2.2
    - text-format == 0.3.1.1
    - yaml == 0.8.23.3

tests:
  unit:
    source-dirs: test
    main: Spec.hs
    dependencies: []
